spring:
  application:
    name: ad-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goormtest
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017 #${MONGODB_URI}
      database: dbfirst #${MONGODB_DATABASE}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://gpadmin:1234@localhost:8761/eureka



server:
  port: 9003

#?db 9000, 3306