apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ad-service-secret
  namespace: ad
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: ad-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ad-service-secret
